name: Check Dependabot PRs

on:
  schedule:
    - cron: '0 0 * * 1'  # Runs every Monday at midnight
  workflow_dispatch:  # Allows manual trigger

jobs:
  check_dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up GitHub CLI
        uses: cli/cli@v2.3.0

      - name: Check for open Dependabot PRs
        run: |
          PRS=$(gh pr list --state open --label dependabot)
          if [ -z "$PRS" ]; then
            echo "No open Dependabot PRs found."
            exit 1  # Fail the job if no PRs are found
          else
            echo "Dependabot PRs found:"
            echo "$PRS"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
